spring.application.name=firstapi


spring.datasource.url=jdbc:sqlserver://IGJ206444:1433;databaseName=DB_ECCOMERCE;encrypt=true;trustServerCertificate=true;integratedSecurity=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username= # Elimina el nombre de usuario, ya que usas autenticación de Windows
spring.datasource.password= # Elimina la contraseña, ya que usas autenticación de Windows
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update  # Asegúrate de tener la configuración correcta de ddl-auto
